name: Build The 8.3 Image Only

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push 8.3
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./8.3/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: toasterlint/php-apache-mysql:8.3-nowarn, toasterlint/php-apache-mysql:8.3
