name: Build The Latest Image Only

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./8.4/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: toasterlint/php-apache-mysql:latest, toasterlint/php-apache-mysql:8.4-nowarn, toasterlint/php-apache-mysql:8.4, toasterlint/php-apache-mysql:8
